feat: add kubeadm

diff --git a/butane/snnipets/node.yaml b/butane/snnipets/node.yaml
--- a/butane/snnipets/node.yaml
+++ b/butane/snnipets/node.yaml
@@ -17,6 +17,25 @@ storage:
         inline: |
           SELINUX=permissive
           SELINUXTYPE=targeted
+    - path: /opt/sbin/fetch-kubeadm
+      mode: 0755
+      contents:
+        inline: |
+          #!bin/sh
+
+          source="${kubeadm_source}"
+          file=/usr/local/bin/kubeadm
+          for i in $(seq 20); do
+            if [ $i -ge 20]; then
+              echo "failed to fetch kubeadm"
+              exit 1
+            fi
+            if curl -sfSL -o "$file" "$source"; then
+              chmod +x "$file"
+              exit 0
+            fi
+            sleep 5
+          done
 systemd:
   units:
     - name: var-mnt-system.mount
@@ -71,3 +90,18 @@ systemd:
 
         [Install]
         WantedBy=local-fs.target
+    - name: setup-kubeadm.service
+      enabled: true
+      contents: |
+        [Unit]
+        Description=Setup kubeadm
+        Wants=network-online.target
+        After=network-online.target
+
+        [Service]
+        Type=oneshot
+        ExecStart=/opt/sbin/fetch-kubeadm
+        RemainAfterExit=yes
+
+        [Install]
+        WantedBy=multi-user.target
